[tool.poetry]
name = "fairqmodel"
version = "2026.05.1"
description = "This repo contains the Python code of the entire life cycle of the air quality model"
authors = ["Henrik Tillkorn <henrik.tillkorn@inwt-statistics.de>, Milan Flach <milan.flach@inwt-statistics.de>"]
readme = "README.md"
packages = [{ include = "fairqmodel" }]


[tool.bumpver]
current_version = "2026.05.1"
version_pattern = "YYYY.0M.PATCH"
commit_message = "bump version to {old_version} -> {new_version}"
tag_message = "v{new_version}"
commit = true
tag = true
push = false

[bumpver.file_patterns]
"poetry.toml" = [
    'version = "{version}"',
    'current_version = "{version}"'
]
"fairqmodel/__init__.py" = [
    '__version__ = "{version}"',
]

[tool.poetry.dependencies]
python = ">=3.11,<3.15"
pandas = "^3.0.2"
xgboost = "^3.2.0"
scikit-learn = "^1.7.2"
tqdm = "^4.67.3"
python-dateutil = "^2.9.0.post0"
pytz-deprecation-shim = "^0.1.0.post0"
retrying = "^1.4.2"
tzdata = "^2026.1"
tzlocal = "^5.3.1"
sqlalchemy = "^2.0.49"
numpy = "^2.4.4"
python-dotenv = "^1.2.1"
clickhouse-connect = "^0.15.1"

[tool.poetry.group.dev.dependencies]
bumpver = "*"
ruff = "*"
black = "*"
mypy = "*"
pytest = "^9.0.3"
cmd2 = "^3.4.0"
flake8 = "^7.3.0"
gunicorn = ">=25.3,<27.0"
iniconfig = "^2.3.0"
ipykernel = "^7.2.0"
isort = "^8.0.1"
matplotlib = "^3.10.7"
optuna = "^4.8.0"
optuna-dashboard = "^0.20.0"
pygments = "^2.20.0"
pyjwt = "^2.12.1"
pyrsistent = "^0.20.0"
pytest-cov = "^7.1.0"
plotly = "^6.6.0"
jupyterlab = "^4.5.6"


[tool.bumpver.file_patterns]
"pyproject.toml" = [
    '^version = "{version}"',
    '^current_version = "{version}"',
]
"fairqmodel/__init__.py" = [
    '^__version__ = "{version}"',
]

[tool.pytest.ini_options]
markers = [
    "local: marks tests that should only run during local development",
]

[tool.ruff]
line-length = 100
target-version = "py310"

[tool.ruff.lint]
select = ["ALL"]
ignore = ["ANN", "COM812", "D", "ISC001"]
per-file-ignores = { "fairq_data_traffic_api/tests/*" = ["S101"] }

[tool.mypy]
ignore_missing_imports = false
exclude = "fairqmodel/notebook_helpers/"

[[tool.mypy.overrides]]
module = [
    "clickhouse_driver",
    "clickhouse_driver.*"
]
ignore_missing_imports = true

[tool.black]
line-length = 120
target-version = ['py39']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''

[tool.flakehell]
base = "https://raw.githubusercontent.com/life4/flakehell/master/pyproject.toml"
baseline = ".flakehell_baseline"
